grafana_secrets:
  env:
    adminPassword: ENC[AES256_GCM,data:FAKE_ENCRYPTED_DATA,iv:FAKE_IV,tag:FAKE_TAG,key:FAKE_KEY_ID]
sops:
  kms:
    - arn: arn:aws:kms:us-east-1:123456789012:key/fake-kms-key-id
      created_at: "2025-06-05T12:00:00Z"
      enc: FAKE_BASE64_ENCRYPTED_KEY
      aws_profile: default
      role: ""
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2025-06-05T12:00:00Z"
  mac: "FAKE_MAC"
  pgp: []
  encrypted_regex: '^(adminPassword)$'
  version: 3.8.1
