grafana_secrets:
  env:
    adminPassword: ENC[AES256_GCM,data:Wk9BZ3pRV2xkcmpBS1FhVQ==,iv:1d3f8c6e71a74f62bdf909e4,tag:3d47f0c9dd60a3a6,key:another-fake-key-id]
sops:
  kms:
    - arn: arn:aws:kms:eu-west-1:987654321098:key/another-fake-kms-key-id
      created_at: "2025-06-05T13:00:00Z"
      enc: ZmFrZV9lbmNyeXB0ZWRfa2V5X2RhdGE=
      aws_profile: ops
      role: arn:aws:iam::987654321098:role/fake-sops-role
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2025-06-05T13:00:00Z"
  mac: "fakegeneratedmacstring1234567890abcdef"
  pgp: []
  encrypted_regex: '^(adminPassword)$'
  version: 3.8.1
